### PR TITLE
this works locally for v3.7.3

### PR DESCRIPTION
**Pull request by ngam**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

works: https://anaconda.org/ngam/singularity
Very similar to the bot pr, but without the deletions.

### CODE REVIEW

**Comment by ngam** [comment]
Looks like we need to update the ubuntu image for the azure pipes

```
##[warning]An image label with the label ubuntu-16.04 does not exist.
,##[error]The remote provider was unable to process the request.
```

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
The files outside of `recipe/` are automatically generated by `conda-smithy` by a process known as "rerendering" the feedstock. You can run `conda smithy rerender` locally or ask the bot to do it for you. In general you should rerender the feedstock whenever you make changes.

Unfortunately singularity is the one weird case where I edit the files by hand after rerendering to make it so that `--privileged` is passed to docker so that user-namespaced containers can be used: https://github.com/conda-forge/singularity-feedstock/commit/3ca1016555163405886bb8a01829838aa2c5f82a

**Comment by ngam** [comment]
> The files outside of `recipe/` are automatically generated by `conda-smithy` by a process known as "rerendering" the feedstock. You can run `conda smithy rerender` locally or ask the bot to do it for you. In general you should rerender the feedstock whenever you make changes.
> 
> Unfortunately singularity is the one weird case where I edit the files by hand after rerendering to make it so that `--privileged` is passed to docker so that user-namespaced containers can be used: [3ca1016](https://github.com/conda-forge/singularity-feedstock/commit/3ca1016555163405886bb8a01829838aa2c5f82a)

Thanks! Clearly it failed after you asked it to rerender, and then it updated all these files. I just went in to update the one line you mentioned, let's see if this clears the issue. I will keep looking to see where the mismatch is happening if it doesn't clear. I think after a few versions, substantial edits are going to be needed to ensure compatibility, but we will get there.

**Comment by ngam** [comment]
Okay, 
- first issue from the rerender: using boa+mamba for build causes aarch64 to fail locally, so reverting back to simply "build" makes it work fine. 
- it seems that the x64 build issue is mainly to do with the image being used (quay.io/condaforge/linux-anvil-comp7). I wonder if we change this to ubuntu or something if that will make the issue go away...

**Comment by ngam** [comment]
based on local tests:
- the rerender's call to let mamba do the build makes it fail for aarch64

based on this (https://github.com/sylabs/singularity/issues/338):
- it seems we have to have a different image for the docker build...

**Comment by chrisburr** [comment]
> first issue from the rerender: using boa+mamba for build causes aarch64 to fail locally, so reverting back to simply "build" makes it work fine.

> it seems that the x64 build issue is mainly to do with the image being used (quay.io/condaforge/linux-anvil-comp7). I wonder if we change this to ubuntu or something if that will make the issue go away...

The image shouldn't be changed, all that we should be taking from there is a glibc version (and CUDA for feedstocks where that applies). All of the other dependencies should be coming from conda-forge else the binaries won't be portable between different linux distributions.

> first issue from the rerender: using boa+mamba for build causes aarch64 to fail locally, so reverting back to simply "build" makes it work fine.

The option to disable it is here: https://conda-forge.org/docs/maintainer/conda_forge_yml.html#build-with-mambabuild

With exception of the `--privileged` quirk you shouldn't need to modify any files other than `recipe/*` and `conda-forge.yml`. Everything else is autogenerated by rerendering.

**Comment by ngam** [comment]
I think the boa+mambabuild is okay. Must be some other underlying issue... See the other pr

Generally, @chrisburr would you want to upload all versions up to the latest or just focus on the latest?

**Comment by chrisburr** [comment]
> would you want to upload all versions up to the latest or just focus on the latest?

I'm happy to just have the latest so feel free to close this and incorporate the comments into your other PR as appropriate. 😃

**Comment by ngam** [comment]
> > would you want to upload all versions up to the latest or just focus on the latest?
> 
> I'm happy to just have the latest so feel free to close this and incorporate the comments into your other PR as appropriate. 😃

Sounds good! I think we are very close to figuring this out.

**Pull request closed without merging**
